### ISSUE TITLE
AttributeError: 'str' object has no attribute 'length' - with current beets

### ISSUE THREAD

**Issue by jhuldtgren** [lcharlick/beets-metalarchives#2]
with beets > 1.4.9 this plugin unfortunately does not work. It fails as candidates() now requires 6 arguments. It throws the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 33, in <module>
    sys.exit(load_entry_point('beets==1.6.0', 'console_scripts', 'beet')())
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1285, in main
    _raw_main(args)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/commands.py", line 943, in import_files
    session.run()
  File "/usr/local/lib/python3.9/site-packages/beets/importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python3.9/site-packages/beets/util/pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.9/site-packages/beets/util/pipeline.py", line 311, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python3.9/site-packages/beets/util/pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python3.9/site-packages/beets/importer.py", line 1376, in lookup_candidates
    task.lookup_candidates()
  File "/usr/local/lib/python3.9/site-packages/beets/importer.py", line 660, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/usr/local/lib/python3.9/site-packages/beets/autotag/match.py", line 461, in tag_album
    for matched_candidate in hooks.album_candidates(items,
  File "/usr/local/lib/python3.9/site-packages/beets/plugins.py", line 573, in decorated
    for v in generator(*args, **kwargs):
  File "/usr/local/lib/python3.9/site-packages/beets/autotag/hooks.py", line 629, in album_candidates
    yield from plugins.candidates(items, artist, album, va_likely,
  File "/usr/local/lib/python3.9/site-packages/beets/plugins.py", line 384, in candidates
    yield from plugin.candidates(items, artist, album, va_likely,
TypeError: candidates() takes 5 positional arguments but 6 were given
```

After poking around the beets code I think this can be fixed as follows:

```
$ diff -u metalarchives.py.orig metalarchives.py
--- metalarchives.py.orig       Fri Jun 10 16:33:13 2022
+++ metalarchives.py    Fri Jun 10 16:36:26 2022
@@ -68,7 +68,7 @@
             dist.add('source', self.config['source_weight'].as_number())
         return dist

-    def candidates(self, items, artist, album, va_likely):
+    def candidates(self, items, artist, album, va_likely, extra_tags=None):
         """Returns a list of AlbumInfo objects for Metal Archives search results
         matching an album and artist (if not various).
         """
```

This gets us further but we run into the following issue now:

```
Candidate: ma-3197 - ma-806463 (Arkona)
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 33, in <module>
    sys.exit(load_entry_point('beets==1.6.0', 'console_scripts', 'beet')())
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1285, in main
    _raw_main(args)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/__init__.py", line 1272, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/commands.py", line 973, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python3.9/site-packages/beets/ui/commands.py", line 943, in import_files
    session.run()
  File "/usr/local/lib/python3.9/site-packages/beets/importer.py", line 340, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python3.9/site-packages/beets/util/pipeline.py", line 446, in run_parallel
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.9/site-packages/beets/util/pipeline.py", line 311, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python3.9/site-packages/beets/util/pipeline.py", line 193, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python3.9/site-packages/beets/importer.py", line 1376, in lookup_candidates
    task.lookup_candidates()
  File "/usr/local/lib/python3.9/site-packages/beets/importer.py", line 660, in lookup_candidates
    autotag.tag_album(self.items, search_ids=self.search_ids)
  File "/usr/local/lib/python3.9/site-packages/beets/autotag/match.py", line 466, in tag_album
    _add_candidate(items, candidates, matched_candidate)
  File "/usr/local/lib/python3.9/site-packages/beets/autotag/match.py", line 372, in _add_candidate
    mapping, extra_items, extra_tracks = assign_items(items, info.tracks)
  File "/usr/local/lib/python3.9/site-packages/beets/autotag/match.py", line 100, in assign_items
    row.append(track_distance(item, track))
  File "/usr/local/lib/python3.9/site-packages/beets/autotag/match.py", line 132, in track_distance
    if track_info.length:
AttributeError: 'str' object has no attribute 'length'
```
So here it's getting further and is getting candidates from MA, but then falls down. I've not found anything obvious (to someone with limited python) to see where this needs to be fixed.

**Comment by DZ945brH** [comment]
I got one step further.
The order of  _return AlbumInfo_ is wrong.
I changed it from
```
        #return AlbumInfo(album.title, album_id, band_names, artist_id, tracks,
        #                 albumtype=album.type, va=False, year=album.year, month=album.date.month,
        #                 day=album.date.day, label=album.label, mediums=album.disc_count,
        #                 country=country, data_source=DATA_SOURCE, data_url=metallum.BASE_URL + '/' + album.url)
```
to
```
        return AlbumInfo(tracks, album.title, album_id, band_names, artist.id,
                         albumtype=album.type, va=False, year=album.year, month=album.date.month,
                         day=album.date.day, label=album.label, mediums=album.disc_count,
                         country=country, data_source=DATA_SOURCE, data_url=metallum.BASE_URL + '/' + album.url)

```

That works a bit, as beets now finds 1(!) album for this given search on metal archives, I guess the first that is returned.
Going for [M]ore Candidates just lists this one found album as well.

![image](https://user-images.githubusercontent.com/42635243/218719968-8d295328-0d01-4054-be9b-6c293e80617f.png)
The correct album would be: https://www.metal-archives.com/albums/Slayer/God_Hates_Us_All/414621
Inserting the ID would just query musicbrainz.

Maybe I'm able to fix the album search later as well...

@lcharlick Are you still here? Can you accept pull requests if we send them? Otherwise we might fork and try to maintain it ourselves.

**Comment by DZ945brH** [comment]
Got it!
I will prepare the pull requests later or in a few days
